layout_spectrum: 0.9660736615769565
typography_spectrum: 0.40531302080489695
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.019338314421474934
  lightness: 0.6986086170654744
  saturation: 0.9147475073114038
  rhythmicContrast: 0.844177020015195
name: Road and Sand
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70708696-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
