name: Road and Sand
favicon: null
layout_spectrum: 0.5912964181043208
typography_spectrum: 0.132483531255275
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4375
  lightness: 0.9897761810570955
  saturation: 0.9407766361255199
  rhythmicContrast: 0.2952966510783881
purpose: []
